services:
  backend:
    image: accvalo/frontend
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    container_name: api.accvalo.shop
    hostname: api.accvalo.shop
    restart: always
    ports:
      - "5000:5000"
