services:
  frontend:
    image: accvalo/frontend
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    container_name: www.accvalo.shop
    hostname: www.accvalo.shop
    restart: always
    ports:
      - "5001:3000"
